### ISSUE TITLE
Error on Load

### ISSUE THREAD

**Issue by RC-Projects** [Limmek/Shitlist#10]
### Is there an existing issue for this?

- [X] I have searched the existing open and closed issues.

### Description

When I launch WoW, I receive two counts of the addon failing. 

### World of Warcraft Flavor

Retail (Default)

### Tested with only Shitlist

- [X] Yes

### Lua Error

```Text
Message: Interface/AddOns/Shitlist/Libs/LibUIDropDownMenu/LibUIDropDownMenu.lua:1 Error loading Interface/AddOns/Shitlist/Libs/LibUIDropDownMenu/LibUIDropDownMenu.lua
Time: Wed Dec 13 17:55:38 2023
Count: 2
```

### Reproduction Steps

1. Enable Shitlist on a character.
2. Login to said character.

**Comment by Limmek** [comment]
Thank you for the bug report. 
The LibUIDropDownMenu is not used and should not have been included in the last release..
6cd76e6

**Comment by Limmek** [comment]
6cd76e6

**Comment by Limmek** [comment]
There is a new update available.

**Comment by RC-Projects** [comment]
Thx!
