### ISSUE TITLE
Overlaps in dropdown menu of friends or guild members🐛 

### ISSUE THREAD

**Issue by JasonDepp** [Limmek/Shitlist#13]
### Is there an existing issue for this?

- [X] I have searched the existing open and closed issues.

### Description

very interesting addon!
found a minor issue, when you right click on a player in friend list or guild member list, or chat window, the menu item is overlapped and not clickable.

found this code in Shitlist.lua:
```
if not (UnitIsPlayer(unit) or (unit == nil and target == "FRIEND" or target == "COMMUNITIES_GUILD_MEMBER")) then
    return
end
```
I guess the original idea is to hide "shitlist" when
1. unit is not a player
2. unit is nil
3. target is my friend
4. target is from my guild/area/chat window

somehow this code statement doesn't block "friend" or "guild"

if what I mentioned above is true, then I suggest to update this into:
```
if not (UnitIsPlayer(unit)) or (unit == nil and target == "FRIEND" or target == "COMMUNITIES_GUILD_MEMBER") then
    return
end
```
with a simple ")" movement

ps: I also tried to disable other addons and keep shitlist only, but it doesn't show anything in menu dropdown (as far as I can see)...
I'm using Shitlist-2.0.3
WOW 3.4.3 zhCN(I added a toc myself)

### World of Warcraft Flavor

Wrath of the Lich King Classic

### Tested with only Shitlist

- [X] Yes

### Reproduction Steps

1. Go to my guild
2. right click on a member's name

### Screenshots

![image](https://github.com/user-attachments/assets/28c1b9d2-05c5-4c1a-8b1f-3a9335c15111)

**Comment by Limmek** [comment]
Great catch i have added the change to the if statement, also created a wrath toc file. 
There is a new 2.0.4 release available.

**Comment by JasonDepp** [comment]
Thank you so much for your quick response!
I would like to contribute to this addon in the future!
Do you develop this addon yourself?
why curseforge removed your addon...
if the reason is related to the shit word...my advise is to rename this addon into something else like "attention list"?
cuz if I'm going to localize it into Chinese Simplified, I would use that name in Chinese...

**Comment by Limmek** [comment]
Sure mate you are more than welcome to submit a translation for the addon if you want to.
Yeah it's only me, the idea cam up when i was playing classic and was annoyed of geting in groups with bad players so i wanted a simple way to make a note on a player to remind my self in the future.

Check this comment https://github.com/Limmek/Shitlist/commit/c6d9146536494307bededb101237b0eca836eb77#commitcomment-144901359 i did a support ticket and asked what i should change but still waiting on a response from them...
I think i will rename the addon to Player Notes or something and change the description a bit, then make a new request and see if it will be approved again.

**Comment by JasonDepp** [comment]
yea Player Notes also makes sense,
curseforge mentioned about impacting other players but it's not the fact... it only reminds "myself" for someone that I like/dislike...
