### ISSUE TITLE
Changes needed to not violate CurseForge ToS

### ISSUE THREAD

**Issue by Limmek** [Limmek/Shitlist#16]
Changes that needs to be addressed before CurseForge will accept the addon again.

- Rename the addon from _Shitlist_ to _Personal Player Notes_.
- Remove the _Announcement_ feature.
- Update the description.

**Comment by JasonDepp** [comment]
Hi Limmek, 
please let me know if you need any support on this one.
feel free to open sub-tasks and assign to me.

**Comment by torkus** [comment]
I just noticed the name change and thought it was funny (I much prefer *Shitlist*. A pox on those Curseforge puritans ;)

In this space there is also:

* HandyNotes
* https://github.com/mikepauer/Carbonite.Notes
* https://github.com/Talryn/CharacterNotes
* https://github.com/Talryn/FriendNotes
* https://github.com/123456687548/PlayerBlacklist
* https://github.com/AlexOvares/Personal-Black-List-PBL
* https://github.com/coolmodi/Hitlist
* https://github.com/Gehennas-EU/blacklist
* https://github.com/qtPyDev/wow_BlacklistTracker

Good luck

**Comment by Limmek** [comment]
Yeah i liked the old name to but apparently not someone at curse forge 😝

**Comment by Limmek** [comment]
@JasonDepp Everything should be done now except the addon description, some new images on curse forge and the zhCH translation need some love to.😁

**Comment by Limmek** [comment]
Curseforge has changed the status to approved, so it is now available on the website and in the client.
