### ISSUE TITLE
Can't Upgrade my Gear without desactivate

### ISSUE THREAD

**Issue by Psych8D** [Limmek/Shitlist#2]
Hello !! First, thanks for this add-on ! I don't understand why people don't use it more :O
So i'v experienced some issues when i try to upgrade my gear, it didn't work, i'v tryed multiple time, and i can do it only when i desactivate this add-on.
I tryed it alone and blizzard text me this in game : https://i.imgur.com/LS5Y4qW.png
That mean "Shitlist have been block because of an action only usable by blizzard UI, you can desactivate it then reload the UI"
Thanks for reading my shitty english >.>

**Comment by Limmek** [comment]
Hi!
I cant reproduce the error, i did try upgrade a piece of armor with both anima and the new "Cataloged Research" points(from 9.1).
The addon is out of date but it is still working. I did try it on both retail and classic and the addon it self works just fine.
One thing i did notice was some of the UI are using the blizzard orginal look even if i use elvui.
