### ISSUE TITLE
 not working for cross realm players

### ISSUE THREAD

**Issue by mohcow** [Limmek/Shitlist#3]
Just wanted to ask if there is an update regarding #1 or will this not happen? I think for a quick fix you could just add the option to edit the player name so users can change the realm themselfs

**Comment by Limmek** [comment]
I have fixed the [issue ](https://github.com/Limmek/Shitlist/commit/0e6aabd5a46f5c123080459d4d3f75d6e01b21f5)now where new players did not save properly.

About the party/guild sync there is no plans atm.
