### ISSUE TITLE
Issues

### ISSUE THREAD

**Issue by Luffty** [Limmek/Shitlist#4]
Hi
I got shitlist a couple of days ago, and i've seem to noticed a few issues.
No minimap icon? Probably not needed, just an observation.

Firstly, the addon does not appear in the drop down list, when right clicking targeted players.
Secondly, the ones i have added manually (Interface>Addons) i'm not warned about.
Thirdly, the shitlist general page have a hard time keeping settings such as audio and party message, when clicking okay and going about my business - only when i click okay and reload does it seem to keep settings.

The reasons and listed players sub menu by themselves seem to be working fine across multiple characters, though without working confirmation upon being partied with a listed player, it's hard to say for sure.

**Comment by Limmek** [comment]
Hello,
Thanks for the bug report.
I have [fixed](https://github.com/Limmek/Shitlist/commit/a74650083e8fbdfaa9caf3cc7431ae61f36d8ee6) the backwards compatibility now. A new update will be available on curse forge soon.

I have no issue with it to keep the settings. Everything is working as expected in 1.1.2 now on both wotlk and retail.
Could you try with only shitlist activated to  see if it resoleve the issue?

**Comment by Luffty** [comment]
The patch is perfect, everything works as intended now :)
As for the settings, I've realized it's my fault - for every change confirmation i need to click okay in the bottom right, as switching between general page and sub menu reverts settings
